# Generated by Django 4.1.2 on 2022-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("username",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(default="", max_length=60),
        ),
    ]
